name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 25
      - name: Install dependencies
        run: npm ci
      - name: Setup environment variables
        run: |
          cp packages/uptime-worker/.dev.vars.example packages/uptime-worker/.dev.vars
      - name: Generate types
        run: |
          # Generate Cloudflare types
          npm run cf-typegen
      - name: Run Linter
        run: npm run lint
      - name: Run TypeScript Check
        run: npm run ts-check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 25
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
